<a href="https://colab.research.google.com/github/MdRufsan/Python/blob/main/learn_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Learn NumPy**
NumPy is a Python library.

NumPy is used for working with arrays.

NumPy is short for "Numerical Python".
fast
need less memory
ndarry object

In [ ]:
!pip install numpy

In [ ]:
import numpy as np

**Arry attributes**

In [ ]:
#1D arry generates
a=np.array([1,2,3])
a

<class 'numpy.ndarray'>


In [ ]:
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
a.shape #arry shape

(3,)

In [ ]:
# dimention name 1D arry=vector
a.ndim

1

In [ ]:
# 2D array
b=np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
type(b)

numpy.ndarray

In [ ]:
b.shape

(2, 3)

In [ ]:
b.ndim

2

**Moer array creation methoda**

In [ ]:
array1=np.array([1,2,3],dtype='int')
array1

array([1, 2, 3])

In [ ]:
z=np.zeros((2,3), order="C", dtype='int')  # ach element will be 0   ((shape),ordre,datatype)
z

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
np.ones((3,3), dtype='int')  # ach element will be 1

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
np.full((3,3),5)  #modify values

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [ ]:
# identity matrix
identity_matrix1=np.eye(4, dtype='int')
identity_matrix1

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [ ]:
identity_matrix2=np.identity(4, dtype='int')
identity_matrix2

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [ ]:
identity_matrix3=np.eye(4,4,1) # (rows,cols,iteration k=1)
identity_matrix3

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [ ]:
# arrange ()
arrange=np.arange(1,10,2) #(start,stop,step)
arrange

array([1, 3, 5, 7, 9])

In [ ]:
linspace=np.linspace(1,10,50,dtype='int') #(start,stop,number of elements)
linspace


array([ 1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  3,  3,  3,  3,  3,  3,
        4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  5,  6,  6,  6,  6,  6,  7,
        7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  9,  9,  9,  9,  9, 10])

In [ ]:
linspace.size

50

In [ ]:
empty=np.empty((2,3))  # entry any value
empty

array([[6.28631005e-316, 0.00000000e+000, 5.31673923e-317],
       [5.31666808e-317, 6.75046004e-310, 6.75046004e-310]])

**Indexing and sliceing**

In [7]:
# generate random integer
import numpy as np
a=np.random.randint(1,100,size=(3,5)) # 1-99 3*5 arry
print(a)

[[66 10 30 27 18]
 [34 37 98 42  3]
 [27 19 36  1  4]]


In [15]:
import numpy as np
a=np.random.randint(1,100,5) # 1-99 integer contains 5 elements in a arry
print(a)

[27 71 59 61  3]


In [22]:
import numpy as np
a=np.random.rand(2,3) # random float
print(a)

[[0.02344438 0.36701947 0.45672275]
 [0.88705298 0.08331896 0.59799164]]


In [26]:
# sorting arry

a=np.array([3,1,7,2,0])
print('The arry is : ',a)
sorted_arr=np.sort(a)
print('The sorted arry is : ',sorted_arr)

The arry is :  [3 1 7 2 0]
The sorted arry is :  [0 1 2 3 7]


In [33]:
# row wise sort in 2D array
a=np.array([[3,1,7],
            [2,0,5]])

sorted_rows=np.sort(a, axis=1)
print('The sorted arry is : ',sorted_arr)

The sorted arry is :  [[1 3 7]
 [0 2 5]]


In [41]:
# summation & multiplication a whole array with a number

a=np.array([[3,2,2],[4,5,6]])

display("Summation 10 : ",a+10)
display("Multiplication 10 : ",a*10)

'Summation 10 : '

array([[13, 12, 12],
       [14, 15, 16]])

'Multiplication 10 : '

array([[30, 20, 20],
       [40, 50, 60]])

In [45]:
row=np.array([1,2,3])
result=a + row
display(result)

array([[4, 4, 5],
       [5, 7, 9]])

In [51]:
#array reshape

arr=np.array([1,2,3,4,5,6])
print('Orginal array :',arr)
reshaped_arr=arr.reshape(2,3) # reshape in 2*3 matrix
print('Reshaped array :',reshaped_arr)

flattened=reshaped_arr.flatten() # return flat again
print('Flattened array :',flattened)

Orginal array : [1 2 3 4 5 6]
Reshaped array : [[1 2 3]
 [4 5 6]]
Flattened array : [1 2 3 4 5 6]


In [59]:
# transpose

a=np.array([[1,2],[5,6]])
print('Orginal array :',a)
transposed=a.T
print('Transposed array :',transposed)

Orginal array : [[1 2]
 [5 6]]
Transposed array : [[1 5]
 [2 6]]


**Indexing and sliceing**

In [60]:
# 1D array indexing

import numpy as np
a=np.array([1,2,3,4,5])
print(a[0])
print(a[-1])

1
5


In [61]:
# 1D array slicing

import numpy as np
a=np.array([1,2,3,4,5])
print(a[0:3])
print(a[2:])

[1 2 3]
[3 4 5]


In [63]:
# 2D array indexing
a=np.array([[1,2,3],[4,5,6]])
print(a[0,1]) # 1st row 2nd col
print(a[1,2]) # 2nd row 3rd col

2
6


In [66]:
# 2D array slicing

a=np.array([[1,2,3],[4,5,6]])
print(a[:,1]) # all rows 2nd col
print(a[0,:]) # 1st row's all cols

[2 5]
[1 2 3]


In [70]:
# boolean indexing (important for filtering)

import numpy as np
a=np.array([1,2,3,4,5,6])
print(a[a>2])

print(a[a%2==0])
print(a[a%2==1])

[3 4 5 6]
[2 4 6]
[1 3 5]


**Array operations**

In [89]:
# arithmetic operations

import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])

print(a+b)
print(a-b)
print(a*b)
print(a/b)


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [88]:
# scalar operations

import numpy as np
a=np.array([1,2,3])
print(a+2)
print(a-2)
print(a*2)
print(a/2)

[3 4 5]
[-1  0  1]
[2 4 6]
[0.5 1.  1.5]


In [87]:
#matrix multiplication (dot product)

import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(a.dot(b))
print(np.dot(a,b))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [86]:
# eliment wise square,power,root

import numpy as np
a=np.array([1,2,3])
print(np.square(a))
print(np.power(a,2))
print(np.sqrt(a))

[1 4 9]
[1 4 9]
[1.         1.41421356 1.73205081]


In [85]:
# aggregate functions

import numpy as np
a=np.array([1,2,3,4,5])
print(np.sum(a))
print(np.mean(a))
print(np.min(a))
print(np.max(a))
print(np.std(a))
print(np.var(a))
print(np.median(a))
print(np.percentile(a,25))
print(np.percentile(a,50))
print(np.percentile(a,75))
print(np.percentile(a,100))
print(np.percentile(a,0))
print(np.percentile(a,5))

15
3.0
1
5
1.4142135623730951
2.0
3.0
2.0
3.0
4.0
5.0
1.0
1.2
